<?php if (isset($component)) { $__componentOriginal9f98b5f781e6741ece0049186c74547f = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9f98b5f781e6741ece0049186c74547f = $attributes; } ?>
<?php $component = Illuminate\View\AnonymousComponent::resolve(['view' => 'components.legal-page','data' => ['title' => 'Acceptable Use Policy','updated' => config('growza-marketing.legal.updated')]] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('legal-page'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\Illuminate\View\AnonymousComponent::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes(['title' => 'Acceptable Use Policy','updated' => \Illuminate\View\Compilers\BladeCompiler::sanitizeComponentAttribute(config('growza-marketing.legal.updated'))]); ?>

    <p>This policy sets out what Growza may and may not be used for. It applies to every account,
    including reseller and agency accounts, and to campaigns placed through the dashboard or the API.</p>

    <h2>1. What Growza does not provide</h2>
    <p>Growza does not supply, and will not accept orders for, any of the following:</p>
    <ul>
        <li>Artificial or automated engagement, including purchased followers, likes, views, streams, subscribers or comments</li>
        <li>Bot traffic, click farms, or engagement generated by automation rather than genuine people</li>
        <li>Any service that requires a customer to supply account passwords or bypass a platform's authentication</li>
        <li>Activity that breaches the terms of service of Instagram, TikTok, YouTube, Facebook, X, LinkedIn, Spotify, Audiomack, SoundCloud or any other platform</li>
        <li>Spam, unsolicited bulk messaging, or scraping of personal data</li>
        <li>Manipulation of reviews, ratings, polls, charts or rankings</li>
    </ul>
    <p>These restrictions are structural. They are not negotiable for larger budgets or enterprise accounts.</p>

    <h2>2. Prohibited content and campaigns</h2>
    <p>You may not use Growza to promote:</p>
    <ul>
        <li>Content that is unlawful in Nigeria or in the territory the campaign targets</li>
        <li>Fraud, financial scams, or deceptive investment schemes</li>
        <li>Content that sexualises or endangers minors</li>
        <li>Harassment, threats, or content inciting violence or hatred against any group</li>
        <li>Counterfeit goods or infringement of another party's intellectual property</li>
        <li>Misinformation about elections, public health, or civic processes</li>
    </ul>

    <h2>3. Account responsibilities</h2>
    <ul>
        <li>You must provide accurate registration details and keep them current</li>
        <li>You are responsible for activity carried out under your account and API credentials</li>
        <li>You must not share credentials or resell access except under an approved reseller or agency arrangement</li>
        <li>You must have the right to promote the content, brand or release you submit</li>
    </ul>

    <h2>4. Enforcement</h2>
    <p>Where we identify a breach we may refuse or cancel an order, suspend or close the account, and where
    required, report the matter to the relevant authority. Our approach to refunds in these circumstances is
    set out in the <a href="<?php echo e(route('legal.refund-policy')); ?>">Refund Policy</a>.</p>

    <h2>5. Reporting a concern</h2>
    <p>If you believe an account is using Growza in breach of this policy, contact us through the
    <a href="<?php echo e(route('contact')); ?>">contact page</a> with the relevant details.</p>

    

 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9f98b5f781e6741ece0049186c74547f)): ?>
<?php $attributes = $__attributesOriginal9f98b5f781e6741ece0049186c74547f; ?>
<?php unset($__attributesOriginal9f98b5f781e6741ece0049186c74547f); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9f98b5f781e6741ece0049186c74547f)): ?>
<?php $component = $__componentOriginal9f98b5f781e6741ece0049186c74547f; ?>
<?php unset($__componentOriginal9f98b5f781e6741ece0049186c74547f); ?>
<?php endif; ?>
<?php /**PATH C:\Users\DELL\growza\growza\resources\views/marketing/legal/acceptable-use.blade.php ENDPATH**/ ?>